server:
  port: 20202
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
mybatis:
  type-aliases-package: com.xhgoo.account.domain
  mapper-locations: classpath*:mapper/*.xml
spring:
  datasource:
    password: huaihz
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://104.161.98.3:3306/microservice
    username: root
